/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpDataforseoApiKeyRouteImport } from './routes/help/dataforseo-api-key'
import { Route as PProjectIdRouteRouteImport } from './routes/p/$projectId/route'
import { Route as PProjectIdIndexRouteImport } from './routes/p/$projectId/index'
import { Route as PProjectIdSavedRouteImport } from './routes/p/$projectId/saved'
import { Route as PProjectIdKeywordsRouteImport } from './routes/p/$projectId/keywords'
import { Route as PProjectIdDomainRouteImport } from './routes/p/$projectId/domain'
import { Route as PProjectIdBacklinksRouteImport } from './routes/p/$projectId/backlinks'
import { Route as PProjectIdAuditRouteImport } from './routes/p/$projectId/audit'
import { Route as PProjectIdAiRouteImport } from './routes/p/$projectId/ai'
import { Route as PProjectIdAuditIndexRouteImport } from './routes/p/$projectId/audit/index'
import { Route as PProjectIdPsiIssuesResultIdRouteImport } from './routes/p/$projectId/psi/issues/$resultId'
import { Route as PProjectIdAuditIssuesResultIdRouteImport } from './routes/p/$projectId/audit/issues/$resultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDataforseoApiKeyRoute = HelpDataforseoApiKeyRouteImport.update({
  id: '/help/dataforseo-api-key',
  path: '/help/dataforseo-api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRouteRoute = PProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdSavedRoute = PProjectIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdKeywordsRoute = PProjectIdKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdDomainRoute = PProjectIdDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdBacklinksRoute = PProjectIdBacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdAuditRoute = PProjectIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdAiRoute = PProjectIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdAuditIndexRoute = PProjectIdAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdAuditRoute,
} as any)
const PProjectIdPsiIssuesResultIdRoute =
  PProjectIdPsiIssuesResultIdRouteImport.update({
    id: '/psi/issues/$resultId',
    path: '/psi/issues/$resultId',
    getParentRoute: () => PProjectIdRouteRoute,
  } as any)
const PProjectIdAuditIssuesResultIdRoute =
  PProjectIdAuditIssuesResultIdRouteImport.update({
    id: '/issues/$resultId',
    path: '/issues/$resultId',
    getParentRoute: () => PProjectIdAuditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/audit': typeof PProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/audit/': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
  '/p/$projectId/psi/issues/$resultId': typeof PProjectIdPsiIssuesResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/audit': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
  '/p/$projectId/psi/issues/$resultId': typeof PProjectIdPsiIssuesResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/audit': typeof PProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/audit/': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
  '/p/$projectId/psi/issues/$resultId': typeof PProjectIdPsiIssuesResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/help/dataforseo-api-key'
    | '/p/$projectId/ai'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId/'
    | '/p/$projectId/audit/'
    | '/p/$projectId/audit/issues/$resultId'
    | '/p/$projectId/psi/issues/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help/dataforseo-api-key'
    | '/p/$projectId/ai'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId'
    | '/p/$projectId/audit'
    | '/p/$projectId/audit/issues/$resultId'
    | '/p/$projectId/psi/issues/$resultId'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId'
    | '/help/dataforseo-api-key'
    | '/p/$projectId/ai'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId/'
    | '/p/$projectId/audit/'
    | '/p/$projectId/audit/issues/$resultId'
    | '/p/$projectId/psi/issues/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdRouteRoute: typeof PProjectIdRouteRouteWithChildren
  HelpDataforseoApiKeyRoute: typeof HelpDataforseoApiKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/dataforseo-api-key': {
      id: '/help/dataforseo-api-key'
      path: '/help/dataforseo-api-key'
      fullPath: '/help/dataforseo-api-key'
      preLoaderRoute: typeof HelpDataforseoApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/saved': {
      id: '/p/$projectId/saved'
      path: '/saved'
      fullPath: '/p/$projectId/saved'
      preLoaderRoute: typeof PProjectIdSavedRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/keywords': {
      id: '/p/$projectId/keywords'
      path: '/keywords'
      fullPath: '/p/$projectId/keywords'
      preLoaderRoute: typeof PProjectIdKeywordsRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/domain': {
      id: '/p/$projectId/domain'
      path: '/domain'
      fullPath: '/p/$projectId/domain'
      preLoaderRoute: typeof PProjectIdDomainRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/backlinks': {
      id: '/p/$projectId/backlinks'
      path: '/backlinks'
      fullPath: '/p/$projectId/backlinks'
      preLoaderRoute: typeof PProjectIdBacklinksRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/audit': {
      id: '/p/$projectId/audit'
      path: '/audit'
      fullPath: '/p/$projectId/audit'
      preLoaderRoute: typeof PProjectIdAuditRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/ai': {
      id: '/p/$projectId/ai'
      path: '/ai'
      fullPath: '/p/$projectId/ai'
      preLoaderRoute: typeof PProjectIdAiRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/audit/': {
      id: '/p/$projectId/audit/'
      path: '/'
      fullPath: '/p/$projectId/audit/'
      preLoaderRoute: typeof PProjectIdAuditIndexRouteImport
      parentRoute: typeof PProjectIdAuditRoute
    }
    '/p/$projectId/psi/issues/$resultId': {
      id: '/p/$projectId/psi/issues/$resultId'
      path: '/psi/issues/$resultId'
      fullPath: '/p/$projectId/psi/issues/$resultId'
      preLoaderRoute: typeof PProjectIdPsiIssuesResultIdRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/audit/issues/$resultId': {
      id: '/p/$projectId/audit/issues/$resultId'
      path: '/issues/$resultId'
      fullPath: '/p/$projectId/audit/issues/$resultId'
      preLoaderRoute: typeof PProjectIdAuditIssuesResultIdRouteImport
      parentRoute: typeof PProjectIdAuditRoute
    }
  }
}

interface PProjectIdAuditRouteChildren {
  PProjectIdAuditIndexRoute: typeof PProjectIdAuditIndexRoute
  PProjectIdAuditIssuesResultIdRoute: typeof PProjectIdAuditIssuesResultIdRoute
}

const PProjectIdAuditRouteChildren: PProjectIdAuditRouteChildren = {
  PProjectIdAuditIndexRoute: PProjectIdAuditIndexRoute,
  PProjectIdAuditIssuesResultIdRoute: PProjectIdAuditIssuesResultIdRoute,
}

const PProjectIdAuditRouteWithChildren = PProjectIdAuditRoute._addFileChildren(
  PProjectIdAuditRouteChildren,
)

interface PProjectIdRouteRouteChildren {
  PProjectIdAiRoute: typeof PProjectIdAiRoute
  PProjectIdAuditRoute: typeof PProjectIdAuditRouteWithChildren
  PProjectIdBacklinksRoute: typeof PProjectIdBacklinksRoute
  PProjectIdDomainRoute: typeof PProjectIdDomainRoute
  PProjectIdKeywordsRoute: typeof PProjectIdKeywordsRoute
  PProjectIdSavedRoute: typeof PProjectIdSavedRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdPsiIssuesResultIdRoute: typeof PProjectIdPsiIssuesResultIdRoute
}

const PProjectIdRouteRouteChildren: PProjectIdRouteRouteChildren = {
  PProjectIdAiRoute: PProjectIdAiRoute,
  PProjectIdAuditRoute: PProjectIdAuditRouteWithChildren,
  PProjectIdBacklinksRoute: PProjectIdBacklinksRoute,
  PProjectIdDomainRoute: PProjectIdDomainRoute,
  PProjectIdKeywordsRoute: PProjectIdKeywordsRoute,
  PProjectIdSavedRoute: PProjectIdSavedRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdPsiIssuesResultIdRoute: PProjectIdPsiIssuesResultIdRoute,
}

const PProjectIdRouteRouteWithChildren = PProjectIdRouteRoute._addFileChildren(
  PProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdRouteRoute: PProjectIdRouteRouteWithChildren,
  HelpDataforseoApiKeyRoute: HelpDataforseoApiKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
